name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install toolchain
      run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - name: Install Trunk
      run: cargo install trunk
    - name: Build with Trunk
      run: trunk build --release --config ios_backup_web --public-url "/ios_backup_explorer/"
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
          path: 'ios_backup_web/dist'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
